apiVersion: apps/v1
kind: Deployment
metadata:
  name: Automated-Backend
spec:
  selector:
    matchLabels:
      app: Automated-Backend
  template:
    metadata:
      labels:
        app: Automated-Backend
    spec:
      containers:
      - name: Automated-Backend
        image: hiruna123/blog-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8060

---
apiVersion: v1
kind: Service
metadata:
  name: Automated-Backend
spec:
  selector:
    app: Automated-Backend
  ports:
  - port: 8060
    targetPort: 8060
  type: LoadBalancer

