name: CI/CD

on:
  push:
    branches:
      - main

env:
  GITHUB_REPO: 'https://github.com/IT21049590/Automated-Backend'
  DOCKER_REPO: 'hiruna123/blog-service'
  EC2_USER: 'ubuntu'
  EC2_HOST: '18.212.70.126'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t $DOCKER_REPO .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push $DOCKER_REPO

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} $EC2_USER@$EC2_HOST "docker pull $DOCKER_REPO"
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} $EC2_USER@$EC2_HOST "docker run -d -p 8060:8060 $DOCKER_REPO"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
